title = "MatLoverによるMatlab以外のブログ"

[author]
name = ""
image = "img/avatar.jpeg"
headline = ""
bio = "機械学習や関連内容のブログです。仕事の依頼などはvikz2713[あっとマーク]gmail.com まで。"
links = [
  { github = "https://github.com/opqrstuvcut" }
]
