[[main]]
  name = "Blog"
  pageRef = "post"
  weight = 10


[[main]]
  pre = "github"
  name = "GitHub"
  url = "https://github.com/opqrstuvcut"
  weight = 30

# [[main]]
#   name = "Topics"
#   pageRef = "topics"
#   weight = 20
